version: '3'
services: 
  frontend: 
    build: 
      context: ./frontend
    container_name: frontend
    image: 403344839207.dkr.ecr.us-west-2.amazonaws.com/frontend
    ports: 
      - "3000:3000"
